"""Word renderer: cover -> TOC -> chapters in manual order (built-ins plus custom text chapters)."""

from __future__ import annotations

import re
from pathlib import Path

from docx import Document
from docx.shared import Inches, RGBColor

from guidegen_engine.render.common import ViewModel, chapter_anchor, md_runs
from guidegen_engine.render.docx.cover import add_cover
from guidegen_engine.render.docx.figure import FigureCounter, add_figure
from guidegen_engine.render.docx.header_footer import add_header_footer
from guidegen_engine.render.docx.headings import apply_styles, heading
from guidegen_engine.render.docx.ox import add_bookmark, add_internal_link, bookmark_name, restart_numbering, set_num
from guidegen_engine.render.docx.table import add_table
from guidegen_engine.render.docx.toc import add_toc


def _rich(doc, text: str | None, style: str | None = None):
    """Paragraphs from the tiny markdown subset (**bold**, *italic*, '- ' lists)."""
    if not text:
        return
    for block in re.split(r"\n\s*\n", text.strip()):
        lines = block.strip().splitlines()
        is_list = all(re.match(r"^\s*([-*]|\d+\.)\s+", ln) for ln in lines)
        num_id = None  # each numbered list starts again at 1
        for ln in (lines if is_list else [" ".join(x.strip() for x in lines)]):
            if is_list:
                numbered = bool(re.match(r"^\s*\d+\.", ln))
                ln = re.sub(r"^\s*([-*]|\d+\.)\s+", "", ln)
                try:
                    p = doc.add_paragraph(style="List Number" if numbered else "List Bullet")
                except KeyError:
                    p = doc.add_paragraph()
                else:
                    if numbered:
                        num_id = num_id or restart_numbering(doc, "List Number")
                        if num_id:
                            set_num(p, num_id)
            else:
                p = doc.add_paragraph(style=style) if style else doc.add_paragraph()
            _runs(p, ln)


def _runs(p, text: str) -> None:
    for t, bold, italic in md_runs(text):
        r = p.add_run(t)
        r.bold = bold or None
        r.italic = italic or None


def render_docx(vm: ViewModel, path: Path) -> Path:
    doc = Document()
    sec = doc.sections[0]
    sec.left_margin = sec.right_margin = Inches(1)
    sec.top_margin = sec.bottom_margin = Inches(0.9)
    apply_styles(doc, vm.primary)
    props = doc.core_properties
    props.title = vm.title
    props.subject = f"{vm.product} user manual"
    props.author = vm.company or vm.product
    props.comments = "Generated by GuideGen"

    add_header_footer(doc, vm)
    add_cover(doc, vm)
    add_toc(doc, vm.primary)
    figs = FigureCounter()

    for cid, ctitle in vm.chapters:
        if not vm.has_chapter(cid):
            continue
        if cid == "getting-started":
            _getting_started(doc, vm, ctitle, figs)
        elif cid == "tasks":
            _tasks(doc, vm, ctitle, figs)
        elif cid == "reference":
            _reference(doc, vm, ctitle, figs)
        elif cid == "troubleshooting":
            heading(doc, ctitle, 1)
            add_table(doc, ["Message", "Cause", "How to fix it"],
                      [[t["message"], t["cause"], t["fix"]] for t in vm.troubleshooting], vm.primary)
        else:  # custom text chapter from the developer's brief or outline (glossary, about this manual...)
            h = heading(doc, ctitle, 1)
            add_bookmark(h, bookmark_name(chapter_anchor(cid)))
            _rich(doc, vm.custom[cid])

    path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(path))
    return path


def _getting_started(doc, vm, title, figs) -> None:
    heading(doc, title, 1)
    gs = vm.getting_started
    if vm.intro:
        _rich(doc, vm.intro)
    if gs["override"]:
        _rich(doc, gs["override"])
        return
    for key, sub in (("requirements", "Before you begin"), ("launch", "Starting the application"), ("sign_in", "Signing in")):
        if gs[key]:
            heading(doc, sub, 2)
            _rich(doc, gs[key])
    if gs["tour"] or gs["tour_figure"]:
        heading(doc, "A quick tour", 2)
        _rich(doc, gs["tour"])
        if gs["tour_figure"]:
            add_figure(doc, gs["tour_figure"], figs)


def _tasks(doc, vm, title, figs) -> None:
    heading(doc, title, 1)
    grouped = vm.tasks_grouped
    for group, tasks in vm.task_groups():
        if grouped:
            heading(doc, group or "Other tasks", 2)
        for t in tasks:
            _task(doc, vm, t, figs, 3 if grouped else 2)


def _task(doc, vm, t, figs, level: int) -> None:
    h = heading(doc, t.title, level)
    add_bookmark(h, bookmark_name(t.anchor))
    if t.goal:
        _rich(doc, t.goal)
    for st in t.steps:
        p = doc.add_paragraph()
        p.paragraph_format.keep_with_next = st.figure is not None
        num = p.add_run(f"Step {st.n}.  ")
        num.bold = True
        num.font.color.rgb = RGBColor.from_string(vm.primary.lstrip("#"))
        _runs(p, st.text)
        if st.figure:
            add_figure(doc, st.figure, figs)
    if t.screens_used:
        p = doc.add_paragraph()
        p.add_run("Screens used: ").bold = True
        for i, (sa, stitle) in enumerate(t.screens_used):
            if i:
                p.add_run(", ")
            add_internal_link(p, stitle, sa, vm.primary)


def _reference(doc, vm, title, figs) -> None:
    heading(doc, title, 1)
    grouped = vm.screens_grouped
    for group, screens in vm.screen_groups():
        if grouped:
            heading(doc, group or "Other screens", 2)
        for s in screens:
            h = heading(doc, s.title, 3 if grouped else 2)
            add_bookmark(h, bookmark_name(s.anchor))
            if s.figure:
                add_figure(doc, s.figure, figs)
            if s.summary:
                _rich(doc, s.summary)
            if s.elements:
                add_table(doc, ["Name", "Type", "What it does"], [[e.name, e.type, e.description] for e in s.elements], vm.primary)
            if s.used_in:
                p = doc.add_paragraph()
                p.add_run("Used in: ").bold = True
                for i, (ta, ttitle) in enumerate(s.used_in):
                    if i:
                        p.add_run(", ")
                    add_internal_link(p, ttitle, ta, vm.primary)
